version: '3'

networks:
  app-tier:
    driver: bridge

services:
  backend:
    build: .
    networks:
      - app-tier
    ports:
      - '3000:3000'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "gallery_app"
      POSTGRES_PORT: "5432"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "gallery_app"
      POSTGRES_PORT: "5432"
    networks:
      - app-tier
